services:
  api:
    container_name: nestjsApi
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      RABBITMQ_URI: ${RABBITMQ_URI}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
      - mq

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_stock_app
    ports:
      - 3306:${DB_PORT}
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    user: "1000:1000"

  mq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:${RABBITMQ_PORT}
      - 15672:${RABBITMQ_ADMIN_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  node_modules:
  mysql_data:
  rabbitmq_data:
