@startuml relations
!include tables.pu

users ||-l-o| profiles : one

roles ||--o{ users : has

' 中間テーブル
users o-u-o{ user_borrowings: has
borrowings o--o{ user_borrowings: many

' 中間テーブル
users o-r-o{ user_comments: many
comments o--o{ user_comments: many

' 中間テーブル
borrowings o-r-o{ borrowing_comments: many
comments o-u-o{ borrowing_comments: many

' 中間テーブル
categories ||-u-o{ item_categories : many
items ||--o{ item_categories : many

stocks o--o items : one
stock_statuses ||-l-o{ stocks : has

stocks ||-l-o{ stock_histories : has
stock_history_statuses ||-u-o{ stock_histories : has

' 中間テーブル
stocks o-l-o{ borrowing_stocks : many
stocks o-u-o{ return_stocks : many

' 中間テーブル
borrowings o-u-o{ borrowing_returns : many
borrowings o-r-o{ borrowing_stocks : many

' 中間テーブル
returns o-r-o{ borrowing_returns : many
returns o--o{ return_stocks : many

statuses ||-l-o{ borrowing_returns : many

@enduml
